### PR TITLE
[#43] Fix Broken Slides From Active Storage Migration

### LINKED ISSUE #43: Fix Broken Slides From ActiveStorage Migration
The main website has switched to using ActiveStorage which changed the JSON response to provide the full URL (i.e including the host such as "www-stage.galter.northwestern.edu") for the images used as slides rather than just providing the endpoint such as "/endpoint/for/file". The fix is to change the `jobs/slides.rb` to not add the host back to the URL and just use what is in the response.

### PR DESCRIPTION
**Pull request by Meowcenary**
closes #43

### CODE REVIEW

File: jobs/slides.rb [hunk 1]
```diff
@@ -9,10 +9,9 @@ class Slides
 
   def image_list
     Net::HTTP.new(@@uri.host, @@uri.port)
-    response = Net::HTTP.get_response(@@uri)
-    JSON.parse(response.body).map {|url|
-      "#{ENV['DASHBOARD_SLIDES_HOST']}/#{url}"
-    }
+    slides_response = Net::HTTP.get_response(@@uri)
+
+    JSON.parse(slides_response.body).map{ |slide_url| slide_url }
```
Comment (sharpattack) [inline jobs/slides.rb:14]: So the slide_url body is the full url now? Nice find and fix.

**Review by sharpattack — APPROVED** [review]
Thanks for the quick fix.

File: jobs/slides.rb (hunk 1 above)
Comment (Meowcenary) [reply jobs/slides.rb:14]: That's exactly it. It was nice that it wasn't something more complicated!
